//! 파일 하나 → 대장 상태 하나. **일곱 중 정확히 하나다.**
//!
//! 분류가 전수 분할이 아니면 대장은 *"무엇을 안 보았는가"* 를 말할 수 없고, 그것이
//! 이 제품의 정체성이다(DESIGN §4). 그래서 이 함수는 **반드시** [`pal_core::FileState`]
//! 하나를 낸다 — 판단이 서지 않는 경우까지 `Unrecognized` 라는 이름의 답이 있다.
//!
//! 순서가 곧 규칙이다:
//!
//! 1. **크기** — 상한을 넘으면 읽지 않는다. `Excluded{oversize}` 이고 **규칙 ID 가 붙는다**
//! 2. **바이너리** — NUL 바이트. git 이 쓰는 것과 같은 판정이다
//! 3. **생성물** — 경로 패턴과 파일 머리 표식이 **둘 다** 있을 때만
//! 4. **언어 인식** — 모르면 `Unrecognized`, 알지만 추출기가 없으면
//!    `Unsupported{NoExtractor}`. `declared` 는 `.gitattributes` 의 `linguist-language`
//!    이고 **확장자를 이긴다** (`recognize` 의 머리 주석)
//! 5. **추출** — 회복이 없으면 `Parsed`. 있으면 `ERROR` 가 삼킨 비율을 본다:
//!    임계를 넘으면 `Unsupported{GrammarDefeated}`, 아니면 `Partial`

use pal_core::{
    BinaryReason, Capable, Containment, ExclusionRuleId, ExtractGrade, FileState,
    GeneratedEvidence, LanguageId, RepoPath, Symbol, UnsupportedReason,
};

use crate::extractor::extractor_for;
use crate::recognize::{Recognition, recognize};
use crate::ExtractError;

/// 파일 크기 상한의 기본값 — stack §5.5 의 자리표시 2MB.
///
/// **실측에서 나온 숫자가 아니다.** 번들·미니파이 파일이 파서를 멈추는 것을 막는
/// 값이고, 넘은 파일은 조용히 사라지지 않고 `Excluded{oversize}` 로 적힌다.
pub const OVERSIZE_BYTES: usize = 2 * 1024 * 1024;

/// 생성물 판정 — **경로 패턴.** 이것만으로는 부족하다.
const GENERATED_PATH_PATTERNS: &[&str] = &["/generated/", "/build/generated/", ".generated."];

/// 생성물 판정 — **파일 머리의 표식.** 이것만으로도 부족하다.
const GENERATED_MARKERS: &[&str] =
    &["Code generated by", "@generated", "DO NOT EDIT", "AUTO-GENERATED", "자동 생성"];

/// 표식을 찾을 파일 머리의 길이.
const MARKER_SCAN_BYTES: usize = 2048;

/// 분류 결과. **1층 캐시가 담는 값이 이것이다** — 그래서 직렬화된다.
///
/// # 왜 포함 관계가 여기 실리는가 (F03-1 · #51)
///
/// `symbol_id` 의 성분 다섯 중 하나가 **컨테이너 체인**이고(F03 §3.2), 그 체인은
/// [`pal_core::FileGraph::contains`] 에서만 나온다. 이 값이 여기 없으면 좌표를 만드는
/// 쪽(`pal-cli::ledger::nodes_of`)이 **캐시 적중일 때 체인을 잃는다** — 그러면 같은
/// 커밋이 캐시 상태에 따라 다른 좌표를 낸다.
///
/// **`FileGraph` 를 통째로 싣지 않는다.** 스코프 체인과 회복 자리는 값이 크고 좌표를
/// 만드는 데 필요하지 않다 — 그 자리는 F02 지붕이 **F04** 로 배정했고 여기서 갚지
/// 않는다. 필요한 것만 싣는 것이 이 값의 규율이다.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct FileOutcome {
    pub state: FileState,
    pub symbols: Vec<Symbol>,
    /// 포함 관계(C1) — [`symbols`] 안의 자리끼리다.
    ///
    /// 최상위만 보는 추출기(Kotlin)에서는 비고 **그것이 정확한 값이다** — 담긴 심볼을
    /// 아예 안 뽑았으므로 담는 관계도 없다.
    ///
    /// [`symbols`]: FileOutcome::symbols
    pub contains: Vec<Containment>,
}

/// 파일 하나를 분류한다.
///
/// # Errors
/// 추출기 자체가 실패하면([`ExtractError`]) — 문법을 붙이지 못하거나 쿼리가 잘못된
/// 경우다. **이것을 상태로 삼키지 않는다.** 일곱 상태 중 어디에도 *"우리 코드가
/// 고장났다"* 는 없고, 그것을 `Unrecognized` 로 적으면 대장이 거짓말을 한다.
pub fn classify(
    path: &RepoPath,
    source: &[u8],
    oversize_bytes: usize,
    declared: Option<&str>,
) -> Result<FileOutcome, ExtractError> {
    let plain = |state| Ok(FileOutcome { state, symbols: Vec::new(), contains: Vec::new() });

    // ① 크기
    if source.len() > oversize_bytes {
        return plain(FileState::Excluded { rule: ExclusionRuleId::new("oversize") });
    }

    // ② 바이너리
    if source.contains(&0) {
        return plain(FileState::Binary { reason: BinaryReason::NulByte });
    }

    // ③ 생성물 — 증거 **둘**
    if let Some(evidence) = generated_evidence(path, source) {
        return plain(FileState::Generated { evidence });
    }

    // ④ 언어
    let language = match recognize(path.extension(), path.file_name(), declared, source) {
        Recognition::Unknown => return plain(FileState::Unrecognized),
        Recognition::Known(id) => {
            return plain(FileState::Unsupported {
                language: id,
                reason: UnsupportedReason::NoExtractor,
            });
        }
        Recognition::FirstClass(l) => l,
    };
    let id = LanguageId::new(language.name());

    // ⑤ 추출 — **빌드되지 않은 언어는 여기서 갈린다**
    //
    // 레지스트리 하나가 능력·추출·등급의 단일 진실이다(`extractor.rs`). 여기서 별도
    // 표를 보면 `pal symbols` 가 답하는 언어와 대장이 `parsed` 로 세는 언어가 갈린다.
    let Capable::Present(extractor) = extractor_for(language) else {
        // 1급 언어인데 이 빌드에 추출기가 없다. **로드맵의 자리다.**
        return plain(FileState::Unsupported {
            language: id,
            reason: UnsupportedReason::NoExtractor,
        });
    };

    let mut graph = extractor.extract(source)?;
    let grade = graph.grade;
    if graph.is_whole() {
        let state = FileState::Parsed { language: id, grade };
        return Ok(FileOutcome {
            state,
            symbols: std::mem::take(&mut graph.symbols),
            contains: graph.contains,
        });
    }

    // ⑥ 임계 강등 — **`partial` 이 문법 부재를 가리지 않게** (F02 §3.4 · `[f02.2.pass]` ④)
    //
    // `partial` 은 *"일부는 읽었다"* 라는 뜻이다. `ERROR` 가 파일을 통째로 삼킨 경우
    // 그 문장은 **거짓이다** — 읽은 것이 없다. 이 코퍼스에서 그 형태가 27 건이고
    // 그중 26 이 선언을 하나도 못 낸다(`PROVISIONAL_ERROR_RATIO_PERCENT` 의 주석).
    //
    // **심볼을 버린다.** 강등된 파일은 *"이 빌드가 못 읽은 파일"* 이고, 그런 파일에서
    // 건진 선언 한둘을 대장에 실으면 **범위가 그만큼 넓어 보인다.** 못 읽었다고 적는
    // 것과 그 파일의 심볼을 싣는 것은 같이 설 수 없다.
    let ratio = graph.error_ratio_percent(source.len());
    if ratio > pal_core::PROVISIONAL_ERROR_RATIO_PERCENT {
        return plain(FileState::Unsupported {
            language: id,
            reason: UnsupportedReason::GrammarDefeated {
                error_ratio_percent: ratio,
                recovery_sites: graph.recovery_count(),
            },
        });
    }

    let state = FileState::Partial { language: id, grade, recovery_sites: graph.recovery_count() };
    Ok(FileOutcome { state, symbols: std::mem::take(&mut graph.symbols), contains: graph.contains })
}

/// 이 빌드가 그 언어에서 **실제로 도달한** 등급.
///
/// **선언 상한이 아니라 실측이다.** stack 이 TypeScript 의 P0 상한을 L2 로 적었지만
/// 그것은 도달 목표이고, 지금 Kotlin 추출기가 뽑는 것은 최상위 선언뿐이라 **L1(구조)**
/// 이다. 상한을 적으면 대장이 없는 능력을 광고한다.
// **팔을 합치지 않는다.** 둘이 같은 값이지 같은 사실이 아니다 — 아래 주석이 그것이고,
// `f01-verify.py` 의 음성 대조가 Kotlin 팔 하나만 L0 으로 떨어뜨려 골든이 잡는지 본다.
// 합치면 그 변이가 두 언어를 한꺼번에 움직여 무엇이 잡혔는지 알 수 없게 된다.
#[allow(clippy::match_same_arms, reason = "언어마다 등급의 근거가 다르고 변이가 하나씩 걸린다")]
#[must_use]
pub const fn grade_of(language: pal_core::Language) -> ExtractGrade {
    match language {
        // S0 의 추출기 — `source_file` 의 직계 자식만 본다. 참조 해소는 없다.
        pal_core::Language::Kotlin => ExtractGrade::L1,
        // F02-3 의 추출기 — 포함 관계 · export/import · **파일 내 스코프 체인(L2a)**.
        // 이름이 어느 선언을 가리키는지 알므로 `body_digest` 가 지역 이름을 지울 수 있고,
        // 그것이 L2 의 뜻이다(R-22).
        //
        // **이것은 여전히 선언 상한이다.** 실제 등급은 심볼에 실린다
        // (`Symbol::identity`) — 구조 분해나 TDZ 가 있는 심볼은 `ordinal` 로 내려앉는다.
        // 언어 표만 남기면 그 심볼들이 성공한 것처럼 보인다.
        //
        // **Kotlin 팔은 L1 그대로다.** 갈라 둔 이유가 이 커밋에서 실현됐다 — 한 팔로
        // 합쳤으면 여기서 Kotlin 이 딸려 올라가 `f01-verify` 의 등급 음성 대조가
        // 무의미해졌을 것이다.
        pal_core::Language::TypeScript => ExtractGrade::L2,
        // 남은 둘(Java · JavaScript)은 추출기가 없으므로 이 함수에 도달하지 않는다.
        pal_core::Language::Java | pal_core::Language::JavaScript => ExtractGrade::L0,
    }
}

/// 경로 패턴과 표식이 **둘 다** 있을 때만 증거가 된다.
///
/// 생성물을 놓치면 그래프가 오염되고, 과잉 판정하면 실코드가 사라진다. 둘 중 하나만으로
/// 판정하면 `build/` 아래의 손으로 쓴 파일이나 *"generated"* 를 언급한 주석이 실코드를
/// 범위 밖으로 밀어낸다.
fn generated_evidence(path: &RepoPath, source: &[u8]) -> Option<GeneratedEvidence> {
    let p = path.as_str();
    let path_pattern = GENERATED_PATH_PATTERNS.iter().find(|pat| p.contains(**pat))?;

    let head_len = source.len().min(MARKER_SCAN_BYTES);
    let head = String::from_utf8_lossy(&source[..head_len]);
    let marker = GENERATED_MARKERS.iter().find(|m| head.contains(**m))?;

    Some(GeneratedEvidence {
        path_pattern: (*path_pattern).to_owned(),
        marker: (*marker).to_owned(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn 분류(path: &str, src: &[u8]) -> FileState {
        classify(&RepoPath::new(path), src, OVERSIZE_BYTES, None).unwrap().state
    }

    #[test]
    fn 널바이트는_바이너리다() {
        assert!(matches!(분류("a.png", b"\x89PNG\x00\x01"), FileState::Binary { .. }));
    }

    #[test]
    fn 크기_상한은_규칙_아이디와_함께_기록된다() {
        // **조용히 사라지지 않는다** — 나중에 "범위가 줄어서 사라진 것"과 구별되어야 한다.
        let big = vec![b'a'; 16];
        let FileState::Excluded { rule } = classify(&RepoPath::new("big.kt"), &big, 8, None).unwrap().state
        else {
            panic!("제외되지 않았다");
        };
        assert_eq!(rule.as_str(), "oversize");
    }

    #[test]
    fn 생성물은_증거가_둘일_때만이다() {
        let marked = b"// Code generated by protoc. DO NOT EDIT.\nclass A";
        // 경로만 — 아니다
        assert!(!matches!(분류("src/generated/A.kt", b"class A"), FileState::Generated { .. }));
        // 표식만 — 아니다
        assert!(!matches!(분류("src/main/A.kt", marked), FileState::Generated { .. }));
        // 둘 다 — 그렇다
        assert!(matches!(분류("src/generated/A.kt", marked), FileState::Generated { .. }));
    }

    #[test]
    fn 아는_언어와_모르는_언어가_갈린다() {
        // 추출기가 없지만 언어는 안다 → 로드맵의 자리
        assert!(matches!(분류("V1.sql", b"select 1"), FileState::Unsupported { .. }));
        // 언어 자체를 모른다 → 설정의 자리
        assert!(matches!(분류("a.bak", b"whatever"), FileState::Unrecognized));
    }

    #[test]
    fn 깨끗한_코틀린은_parsed_다() {
        let FileState::Parsed { language, grade } = 분류("A.kt", b"class A\nfun b() {}\n") else {
            panic!("parsed 가 아니다");
        };
        assert_eq!(language.as_str(), "Kotlin");
        assert_eq!(grade, ExtractGrade::L1);
    }

    #[test]
    fn 회복이_있으면_partial_이다() {
        // 성한 부분이 대부분이고 깨진 곳이 작다 — **부분 결과가 실제로 있는** 경우다.
        let mut src = "class A\nfun b() {}\nclass C\nfun d() {}\n".repeat(20);
        src.push_str("@@@\n");
        let FileState::Partial { recovery_sites, .. } = 분류("A.kt", src.as_bytes()) else {
            panic!("partial 이 아니다");
        };
        assert!(recovery_sites > 0);
    }

    #[test]
    fn error_가_파일을_삼키면_partial_이_아니라_강등이다() {
        // **`partial` 은 *"일부는 읽었다"* 라는 뜻이고 여기서 그 문장은 거짓이다.**
        // 실물에서 이 형태가 27 건이고 그중 26 이 선언을 하나도 못 낸다(`[f02.2.pass]` ④).
        let out = classify(&RepoPath::new("A.kt"), b"@@@ !!! @@@ ??? &&&", OVERSIZE_BYTES, None)
            .unwrap();
        let FileState::Unsupported { language, reason } = out.state else {
            panic!("강등되지 않았다");
        };
        assert_eq!(language.as_str(), "Kotlin");
        let UnsupportedReason::GrammarDefeated { error_ratio_percent, recovery_sites } = reason
        else {
            panic!("이유가 `추출기 없음` 으로 뭉개졌다 — 그 언어의 추출기는 있다");
        };
        assert!(error_ratio_percent > pal_core::PROVISIONAL_ERROR_RATIO_PERCENT);
        assert!(recovery_sites > 0, "강등의 근거가 산출에 안 남았다");
        assert!(out.symbols.is_empty(), "못 읽었다고 적고 그 파일의 심볼을 실었다");
    }

    #[test]
    fn 추출기가_없는_것과_문법이_못_읽은_것은_다른_이유다() {
        // **뭉개면 대장 머리가 「추출기 없음」이라 적고 사용자가 로드맵에서 고칠 곳을 찾는다.**
        let FileState::Unsupported { reason, .. } = 분류("V1.sql", b"select 1") else {
            panic!("unsupported 가 아니다");
        };
        assert_eq!(reason, UnsupportedReason::NoExtractor);
    }

    #[test]
    fn 강등은_비율이지_자리의_수가_아니다() {
        // 자리가 여럿이어도 삼킨 넓이가 작으면 **부분 결과가 있다** — 강등하지 않는다.
        let mut src = "class A\nfun b() {}\n".repeat(60);
        src.push_str("@\n@\n@\n");
        assert!(matches!(분류("A.kt", src.as_bytes()), FileState::Partial { .. }));
    }

    fn 요약(src: &str) -> pal_core::BodyDigest {
        let out = classify(&RepoPath::new("A.kt"), src.as_bytes(), OVERSIZE_BYTES, None).unwrap();
        out.symbols[0].body
    }

    #[test]
    fn 포매팅과_주석은_요약을_바꾸지_않는다() {
        // **R-07 의 거짓 양성이 죽는 자리다.** 포매터 커밋 하나에 결박이 무더기로
        // stale 이 되면 사람이 표시를 무시하고, 그러면 제품이 죽는다.
        let 원본 = "fun greet(name: String): String {\n    return \"hi\"\n}\n";
        let 포매팅만 = "fun   greet( name : String ) : String {\n\n\treturn \"hi\"\n\n}\n";
        let 주석추가 = "// 인사한다\nfun greet(name: String): String {\n    /* 왜냐하면 */ return \"hi\"\n}\n";
        let 세미콜론 = "fun greet(name: String): String {\n    return \"hi\";\n}\n";
        assert_eq!(요약(원본), 요약(포매팅만), "공백·줄바꿈이 요약을 바꿨다");
        assert_eq!(요약(원본), 요약(주석추가), "주석이 요약을 바꿨다");
        assert_eq!(요약(원본), 요약(세미콜론), "선택적 세미콜론이 요약을 바꿨다");
    }

    #[test]
    fn 의미가_바뀌면_요약이_바뀐다() {
        // **양방향이어야 한다.** 앞의 시험만 통과하는 것은 상수를 돌려주는 요약이고,
        // 그것은 아무것도 감지하지 못한다.
        let 원본 = "fun greet(name: String): String {\n    return \"hi\"\n}\n";
        assert_ne!(요약(원본), 요약("fun greet(name: String): String {\n    return \"bye\"\n}\n"),
                   "반환값이 바뀌었는데 요약이 같다");
        assert_ne!(요약(원본), 요약("fun greet(name: Int): String {\n    return \"hi\"\n}\n"),
                   "파라미터 타입이 바뀌었는데 요약이 같다");
        assert_ne!(요약(원본), 요약("fun greet(name: String): String {\n    log()\n    return \"hi\"\n}\n"),
                   "본문에 호출이 늘었는데 요약이 같다");
    }

    #[test]
    fn 토큰_경계가_지켜진다() {
        // 구분자가 없으면 `fun f` 와 `funf` 가 같은 바이트열이 된다.
        assert_ne!(요약("fun f() {}\n"), 요약("class funf\n"));
    }

    #[test]
    fn 변수명은_지우지_않는다() {
        // **R-22** — 스코프 해소(L2)가 없는데 지우면 서로 다른 코드가 같은 요약을 갖는다.
        // 이 추출기는 L1 이므로 지우지 않는 것이 옳다.
        assert_ne!(요약("fun f() {\n  val a = 1\n}\n"), 요약("fun f() {\n  val b = 1\n}\n"));
    }

    #[test]
    fn 포함_관계가_분류와_함께_나온다() {
        // **캐시가 담는 값이다** — 없으면 좌표를 만드는 쪽이 캐시 적중일 때 컨테이너
        // 체인을 잃고, 그러면 같은 커밋이 캐시 상태에 따라 다른 좌표를 낸다(#51).
        let out =
            classify(&RepoPath::new("a.ts"), b"class C { m() {} }", OVERSIZE_BYTES, None).unwrap();
        assert_eq!(out.symbols.len(), 2, "클래스와 메서드가 나와야 한다");
        assert_eq!(out.contains.len(), 1, "메서드가 클래스에 담긴 관계가 안 실렸다");
    }

    #[test]
    fn 최상위만_보는_추출기는_포함_관계가_빈다() {
        // **빈 것이 정확한 값이다** — 담긴 심볼을 아예 안 뽑았으므로 담는 관계도 없다.
        let out = classify(&RepoPath::new("A.kt"), b"class A\nfun b() {}\n", OVERSIZE_BYTES, None)
            .unwrap();
        assert!(out.contains.is_empty());
    }

    #[test]
    fn 강등된_파일은_포함_관계도_버린다() {
        // 심볼을 버리는데 관계를 남기면 그 관계가 **없는 자리**를 가리킨다.
        let out = classify(&RepoPath::new("A.kt"), b"@@@ !!! @@@ ??? &&&", OVERSIZE_BYTES, None)
            .unwrap();
        assert!(out.symbols.is_empty());
        assert!(out.contains.is_empty(), "심볼은 버리고 관계는 남겼다 — 자리가 어긋난다");
    }

    #[test]
    fn 심볼은_분류와_함께_나온다() {
        // 1층 캐시가 담을 값이다 — 분류만 캐시하면 두 번째 실행에서 심볼이 사라진다.
        let out = classify(&RepoPath::new("A.kt"), b"class A\nclass B\n", OVERSIZE_BYTES, None).unwrap();
        assert_eq!(out.symbols.len(), 2);
    }
}
