//! 파일 하나 → 대장 상태 하나. **일곱 중 정확히 하나다.**
//!
//! 분류가 전수 분할이 아니면 대장은 *"무엇을 안 보았는가"* 를 말할 수 없고, 그것이
//! 이 제품의 정체성이다(DESIGN §4). 그래서 이 함수는 **반드시** [`pal_core::FileState`]
//! 하나를 낸다 — 판단이 서지 않는 경우까지 `Unrecognized` 라는 이름의 답이 있다.
//!
//! 순서가 곧 규칙이다:
//!
//! 1. **크기** — 상한을 넘으면 읽지 않는다. `Excluded{oversize}` 이고 **규칙 ID 가 붙는다**
//! 2. **바이너리** — NUL 바이트. git 이 쓰는 것과 같은 판정이다
//! 3. **생성물** — 경로 패턴과 파일 머리 표식이 **둘 다** 있을 때만
//! 4. **언어 인식** — 모르면 `Unrecognized`, 알지만 추출기가 없으면 `Unsupported`
//! 5. **추출** — 회복이 있었으면 `Partial`, 아니면 `Parsed`

use pal_core::{
    BinaryReason, Capable, ExclusionRuleId, ExtractGrade, FileState, GeneratedEvidence,
    LanguageId, RepoPath, Symbol,
};

use crate::recognize::{Recognition, recognize};
use crate::{ExtractError, extract_detailed};

/// 파일 크기 상한의 기본값 — stack §5.5 의 자리표시 2MB.
///
/// **실측에서 나온 숫자가 아니다.** 번들·미니파이 파일이 파서를 멈추는 것을 막는
/// 값이고, 넘은 파일은 조용히 사라지지 않고 `Excluded{oversize}` 로 적힌다.
pub const OVERSIZE_BYTES: usize = 2 * 1024 * 1024;

/// 생성물 판정 — **경로 패턴.** 이것만으로는 부족하다.
const GENERATED_PATH_PATTERNS: &[&str] = &["/generated/", "/build/generated/", ".generated."];

/// 생성물 판정 — **파일 머리의 표식.** 이것만으로도 부족하다.
const GENERATED_MARKERS: &[&str] =
    &["Code generated by", "@generated", "DO NOT EDIT", "AUTO-GENERATED", "자동 생성"];

/// 표식을 찾을 파일 머리의 길이.
const MARKER_SCAN_BYTES: usize = 2048;

/// 분류 결과. **1층 캐시가 담는 값이 이것이다** — 그래서 직렬화된다.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct FileOutcome {
    pub state: FileState,
    pub symbols: Vec<Symbol>,
}

/// 파일 하나를 분류한다.
///
/// # Errors
/// 추출기 자체가 실패하면([`ExtractError`]) — 문법을 붙이지 못하거나 쿼리가 잘못된
/// 경우다. **이것을 상태로 삼키지 않는다.** 일곱 상태 중 어디에도 *"우리 코드가
/// 고장났다"* 는 없고, 그것을 `Unrecognized` 로 적으면 대장이 거짓말을 한다.
pub fn classify(
    path: &RepoPath,
    source: &[u8],
    oversize_bytes: usize,
) -> Result<FileOutcome, ExtractError> {
    let plain = |state| Ok(FileOutcome { state, symbols: Vec::new() });

    // ① 크기
    if source.len() > oversize_bytes {
        return plain(FileState::Excluded { rule: ExclusionRuleId::new("oversize") });
    }

    // ② 바이너리
    if source.contains(&0) {
        return plain(FileState::Binary { reason: BinaryReason::NulByte });
    }

    // ③ 생성물 — 증거 **둘**
    if let Some(evidence) = generated_evidence(path, source) {
        return plain(FileState::Generated { evidence });
    }

    // ④ 언어
    let language = match recognize(path.extension(), path.file_name()) {
        Recognition::Unknown => return plain(FileState::Unrecognized),
        Recognition::Known(id) => return plain(FileState::Unsupported { language: id }),
        Recognition::FirstClass(l) => l,
    };
    let id = LanguageId::new(language.name());

    // ⑤ 추출 — **빌드되지 않은 언어는 여기서 갈린다**
    let Capable::Present(()) = crate::capability(language) else {
        // 1급 언어인데 이 빌드에 추출기가 없다. `unsupported` 가 정확히 그 뜻이다.
        return plain(FileState::Unsupported { language: id });
    };

    let extraction = extract_detailed(source)?;
    let grade = grade_of(language);
    let state = if extraction.recovery_sites == 0 {
        FileState::Parsed { language: id, grade }
    } else {
        FileState::Partial { language: id, grade, recovery_sites: extraction.recovery_sites }
    };
    Ok(FileOutcome { state, symbols: extraction.symbols })
}

/// 이 빌드가 그 언어에서 **실제로 도달한** 등급.
///
/// **선언 상한이 아니라 실측이다.** stack 이 TypeScript 의 P0 상한을 L2 로 적었지만
/// 그것은 도달 목표이고, 지금 Kotlin 추출기가 뽑는 것은 최상위 선언뿐이라 **L1(구조)**
/// 이다. 상한을 적으면 대장이 없는 능력을 광고한다.
#[must_use]
pub const fn grade_of(language: pal_core::Language) -> ExtractGrade {
    match language {
        // S0 의 추출기 — `source_file` 의 직계 자식만 본다. 참조 해소는 없다.
        pal_core::Language::Kotlin => ExtractGrade::L1,
        // 나머지 셋은 추출기가 없으므로 이 함수에 도달하지 않는다.
        _ => ExtractGrade::L0,
    }
}

/// 경로 패턴과 표식이 **둘 다** 있을 때만 증거가 된다.
///
/// 생성물을 놓치면 그래프가 오염되고, 과잉 판정하면 실코드가 사라진다. 둘 중 하나만으로
/// 판정하면 `build/` 아래의 손으로 쓴 파일이나 *"generated"* 를 언급한 주석이 실코드를
/// 범위 밖으로 밀어낸다.
fn generated_evidence(path: &RepoPath, source: &[u8]) -> Option<GeneratedEvidence> {
    let p = path.as_str();
    let path_pattern = GENERATED_PATH_PATTERNS.iter().find(|pat| p.contains(**pat))?;

    let head_len = source.len().min(MARKER_SCAN_BYTES);
    let head = String::from_utf8_lossy(&source[..head_len]);
    let marker = GENERATED_MARKERS.iter().find(|m| head.contains(**m))?;

    Some(GeneratedEvidence {
        path_pattern: (*path_pattern).to_owned(),
        marker: (*marker).to_owned(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn 분류(path: &str, src: &[u8]) -> FileState {
        classify(&RepoPath::new(path), src, OVERSIZE_BYTES).unwrap().state
    }

    #[test]
    fn 널바이트는_바이너리다() {
        assert!(matches!(분류("a.png", b"\x89PNG\x00\x01"), FileState::Binary { .. }));
    }

    #[test]
    fn 크기_상한은_규칙_아이디와_함께_기록된다() {
        // **조용히 사라지지 않는다** — 나중에 "범위가 줄어서 사라진 것"과 구별되어야 한다.
        let big = vec![b'a'; 16];
        let FileState::Excluded { rule } = classify(&RepoPath::new("big.kt"), &big, 8).unwrap().state
        else {
            panic!("제외되지 않았다");
        };
        assert_eq!(rule.as_str(), "oversize");
    }

    #[test]
    fn 생성물은_증거가_둘일_때만이다() {
        let marked = b"// Code generated by protoc. DO NOT EDIT.\nclass A";
        // 경로만 — 아니다
        assert!(!matches!(분류("src/generated/A.kt", b"class A"), FileState::Generated { .. }));
        // 표식만 — 아니다
        assert!(!matches!(분류("src/main/A.kt", marked), FileState::Generated { .. }));
        // 둘 다 — 그렇다
        assert!(matches!(분류("src/generated/A.kt", marked), FileState::Generated { .. }));
    }

    #[test]
    fn 아는_언어와_모르는_언어가_갈린다() {
        // 추출기가 없지만 언어는 안다 → 로드맵의 자리
        assert!(matches!(분류("V1.sql", b"select 1"), FileState::Unsupported { .. }));
        // 언어 자체를 모른다 → 설정의 자리
        assert!(matches!(분류("a.bak", b"whatever"), FileState::Unrecognized));
    }

    #[test]
    fn 깨끗한_코틀린은_parsed_다() {
        let FileState::Parsed { language, grade } = 분류("A.kt", b"class A\nfun b() {}\n") else {
            panic!("parsed 가 아니다");
        };
        assert_eq!(language.as_str(), "Kotlin");
        assert_eq!(grade, ExtractGrade::L1);
    }

    #[test]
    fn 회복이_있으면_partial_이다() {
        // 닫히지 않은 괄호 — tree-sitter 가 오류 회복한다.
        let FileState::Partial { recovery_sites, .. } = 분류("A.kt", b"class A { fun b( {")
        else {
            panic!("partial 이 아니다");
        };
        assert!(recovery_sites > 0);
    }

    fn 요약(src: &str) -> pal_core::BodyDigest {
        let out = classify(&RepoPath::new("A.kt"), src.as_bytes(), OVERSIZE_BYTES).unwrap();
        out.symbols[0].body
    }

    #[test]
    fn 포매팅과_주석은_요약을_바꾸지_않는다() {
        // **R-07 의 거짓 양성이 죽는 자리다.** 포매터 커밋 하나에 결박이 무더기로
        // stale 이 되면 사람이 표시를 무시하고, 그러면 제품이 죽는다.
        let 원본 = "fun greet(name: String): String {\n    return \"hi\"\n}\n";
        let 포매팅만 = "fun   greet( name : String ) : String {\n\n\treturn \"hi\"\n\n}\n";
        let 주석추가 = "// 인사한다\nfun greet(name: String): String {\n    /* 왜냐하면 */ return \"hi\"\n}\n";
        let 세미콜론 = "fun greet(name: String): String {\n    return \"hi\";\n}\n";
        assert_eq!(요약(원본), 요약(포매팅만), "공백·줄바꿈이 요약을 바꿨다");
        assert_eq!(요약(원본), 요약(주석추가), "주석이 요약을 바꿨다");
        assert_eq!(요약(원본), 요약(세미콜론), "선택적 세미콜론이 요약을 바꿨다");
    }

    #[test]
    fn 의미가_바뀌면_요약이_바뀐다() {
        // **양방향이어야 한다.** 앞의 시험만 통과하는 것은 상수를 돌려주는 요약이고,
        // 그것은 아무것도 감지하지 못한다.
        let 원본 = "fun greet(name: String): String {\n    return \"hi\"\n}\n";
        assert_ne!(요약(원본), 요약("fun greet(name: String): String {\n    return \"bye\"\n}\n"),
                   "반환값이 바뀌었는데 요약이 같다");
        assert_ne!(요약(원본), 요약("fun greet(name: Int): String {\n    return \"hi\"\n}\n"),
                   "파라미터 타입이 바뀌었는데 요약이 같다");
        assert_ne!(요약(원본), 요약("fun greet(name: String): String {\n    log()\n    return \"hi\"\n}\n"),
                   "본문에 호출이 늘었는데 요약이 같다");
    }

    #[test]
    fn 토큰_경계가_지켜진다() {
        // 구분자가 없으면 `fun f` 와 `funf` 가 같은 바이트열이 된다.
        assert_ne!(요약("fun f() {}\n"), 요약("class funf\n"));
    }

    #[test]
    fn 변수명은_지우지_않는다() {
        // **R-22** — 스코프 해소(L2)가 없는데 지우면 서로 다른 코드가 같은 요약을 갖는다.
        // 이 추출기는 L1 이므로 지우지 않는 것이 옳다.
        assert_ne!(요약("fun f() {\n  val a = 1\n}\n"), 요약("fun f() {\n  val b = 1\n}\n"));
    }

    #[test]
    fn 심볼은_분류와_함께_나온다() {
        // 1층 캐시가 담을 값이다 — 분류만 캐시하면 두 번째 실행에서 심볼이 사라진다.
        let out = classify(&RepoPath::new("A.kt"), b"class A\nclass B\n", OVERSIZE_BYTES).unwrap();
        assert_eq!(out.symbols.len(), 2);
    }
}
